version: '2'
services:
  php:
    container_name: "site-php"
    build: ./bin/docker_containers/php
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./homepage:/var/www/html
    ports:
      - "25252:80" # RandomNumber
